"""empty message

Revision ID: a538f967ecd8
Revises: c6866b4d54a1
Create Date: 2024-08-31 22:37:14.476444

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a538f967ecd8'
down_revision = 'c6866b4d54a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=6),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.String(length=6),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
